### PR TITLE
Integration Specs

### PR DESCRIPTION
**Pull request by bushmusi**
> # Below features have been integrated

1. Use Capybara to write integration tests for each view in your project.
2. User **index**, **show**, and **post** page testing have been added
3. Post **show** page integration testing have been added
**NB:** For testing it will be better if you  run: ``bundle exec rspec``
Screenshot from 2022-06-25 17-40-21

### Happy CR :eyes:

### CODE REVIEW

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi @bushmusi, @Tufahel and @iLynette,

✔️ Use of capybara

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Some of your tests are failing. Kindly fix them.

  bushra-test

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bushmusi** [comment]
Hi @DammyShittu, Thanks for your CR. But all tests are passing in my machine I don't know how it happens on your machine.
### **Kindly**: Can you check it again using below command
**Run:** ``bundle exec rspec``
Screenshot from 2022-06-25 17-40-21

**Review by EricMbouwe — APPROVED** [review]
Hi @bushmusi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bushmusi** [comment]
> Hi @DammyShittu, Thanks for your CR. But all tests are passing in my machine I don't know how it happens on your machine.
> 
> ### **Kindly**: Can you check it again using below command
> **Run:** `bundle exec rspec` Screenshot from 2022-06-25 17-40-21

@DammyShittu I run on other machine and you were right :+1:

**Pull request merged**
